name: 'Changelog updater'
author: 'jeabapLANG'
description: 'Automatically updates a changelog with the latest changes made to a repository'

inputs:
  dynamicContent:
    description: 'Dynamic content to update the variables from'
  actionType:
    description: 'Type of action to perform on a dynamic content'
  variableStartTag:
    description: 'Start tag to detect the start of a variable field'
  variableStopTag:
    description: 'Stop tag to detect the stop of a variable field'
  variableName:
    description: 'Name of the specified variable to update'
  variableValue:
    description: 'Value for the specified variable to update'

runs:
  using: 'node20'
  main: 'main.js'