name: 'Markdown updater'
author: 'xaynecast'
description: 'Automatically updates a markdown file with the specified values to a repository'

inputs:
  secret_token:
    description: 'Token to use for the operations'
    required: true

runs:
  using: 'node16'
  main: 'main.js'
