name: 'Deploy Site'

on:
  push:
    branches:
    - 'main' # Only trigger on the development branch

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Perform checkout'
      uses: 'actions/checkout@v2'
    - name: 'Show dir'
      uses: 'ls'
    - name: 'Update changelog'
      uses: './action.yml'
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        changelog_path: './CHANGELOG.md'
