name: 'Deploy Site'

on:
  push:
    branches:
    - 'main' # Only trigger on the development branch

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions: 'write-all'
    steps:
    - name: 'Perform checkout'
      uses: 'actions/checkout@v2'
    - name: 'Show dir'
      run: 'ls'
    - name: 'Update changelog'
      uses: './'
      with:
        file_path: 'test.md'
        action_type: 'modify'
        variable: 'MY_VARIABLE'
        value: '${{ github.event.commits[0].author.name }} ${{ github.event.commits[0].message }}'
