name: 'Deploy Site'

on:
  push:
    branches:
    - 'main' # Only trigger on the development branch

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions: 'write-all'
    outputs:
      outputContent: ${{ steps.modifyContent.outputs.value }}
      outputTest: ${{ steps.step1.outputs.value }}
    steps:
    - id: step1
      run: echo "value=world" >> "$GITHUB_OUTPUT"
    - name: Summary
      run: |
        {
          echo "### Workflow variables"
          echo "| Variable   | Value       |"
          echo "| ---------- | ----------- |"
          echo "| env_token  | $env_token  |"
          echo "| env_domain | $env_domain |"
        } >> $GITHUB_STEP_SUMMARY
    - name: 'Perform checkout'
      uses: 'actions/checkout@v2'
    - id: 'modifyContent'
      name: 'Update changelog'
      uses: './'
      with:
        secretToken: '${{ secrets.GITHUB_TOKEN }}'
        itemOwner: 'XayneCast'
        itemRepository: 'actiontest'
        itemPath: 'test.md'
        actionType: 'MODIFICATION'
        commitMessage: 'My commit !'
        modificationType: 'SET'
        variableStartTag: '<!--{{'
        variableStopTag: '}}-->'
        variableName: 'MY_VARIABLE'
        variableValue: 'NEW ${{ github.event.commits[0].author.name }} ${{ github.event.commits[0].message }}'
  get:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.outputContent}}
          OUTPUT2: ${{needs.build.outputs.outputTest}}
        run: echo "|$OUTPUT1| |$OUTPUT2|"
