name: 'Deploy Site'

on:
  push:
    branches:
    - 'main' # Only trigger on the development branch

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions: 'write-all'
    outputs:
      outputContent: ${{ steps.modifyContent.outputs.result }}
      outputValue1: ${{ steps.modifyContent.outputs.VALUE1 }}
    steps:
    - id: step1
      run: echo "value=world" >> "$GITHUB_OUTPUT"
    - name: Summary
      run: |
        {
          echo "### Workflow variables"
          echo "| Variable   | Value       |"
          echo "| ---------- | ----------- |"
          echo "| env_token  | $env_token  |"
          echo "| env_domain | $env_domain |"
        } >> $GITHUB_STEP_SUMMARY
    - name: 'Perform checkout'
      uses: 'actions/checkout@v2'
    - id: 'modifyContent'
      name: 'Update changelog'
      uses: './'
      with:
        payload: '<!--{{ MY_VARIABLE }}-->TEST<!--{{ MY_VARIABLE }}-->'
        actionType: 'GET'
        variableStartTag: '<!--{{'
        variableStopTag: '}}-->'
        variableName: 'MY_VARIABLE'
        variableValue: 'NEW ${{ github.event.commits[0].author.name }} ${{ github.event.commits[0].message }}'
  get:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.outputContent}}
          VALUE1: ${{needs.build.outputs.outputValue1}}
        run: echo "|$OUTPUT1| |$VALUE1|"
