name: 'Deploy Site'

on:
  push:
    branches:
    - 'main' # Only trigger on the development branch

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions: 'write-all'
    steps:
    - name: 'Perform checkout'
      uses: 'actions/checkout@v2'
    - name: 'Update changelog'
      uses: './'
      with:
        secretToken: '${{ secrets.GITHUB_TOKEN }}'
        itemOwner: 'XayneCast'
        itemRepository: 'actiontest'
        itemPath: 'test.md'
        actionType: 'MODIFICATION'
        commitMessage: 'My commit !'
        modificationType: 'SET'
        variableStartTag: '<!--{{'
        variableStopTag: '}}-->'
        variableName: 'MY_VARIABLE'
        variableValue: 'NEW ${{ github.event.commits[0].author.name }} ${{ github.event.commits[0].message }}'
